table Dim_Vendedor
	lineageTag: 9c9788e2-6771-4e1d-8e1d-0aaab5ded953

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 965a7d04-ce67-4325-9791-45e0b2961709
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 7f48296a-4497-41fa-b0ed-c32544efa479
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c8ab2e8-8031-425a-b423-57aac8ff37b9
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: a85a450f-c070-4065-9ad1-4b090d371a93
			defaultHierarchy: LocalDateTable_bee6e1c6-3248-4a41-939f-ab19ffb3d1fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: b37b8caf-0a4b-4de2-afb1-fa609d01d747
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendedor = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Andreé Torres\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Vendedor_Table = Origen{[Item="Dim_Vendedor",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Vendedor_Table,{{"ID_Vendedor", Int64.Type}, {"Vendedor", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

