table Hoja1
	lineageTag: ab707e20-2528-448f-a145-ba61ab3eabe5

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ec495f4-04b7-4cfb-b67b-6cfa0b1a3bac
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: ca103909-052c-400b-846c-a715d760f503
			defaultHierarchy: LocalDateTable_e9218bf4-bf2f-43ae-a89f-dec33d2a4900.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 8eb66a96-8fec-42c7-8e93-935605bdc493
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: cbaba5e1-2d45-4c42-a139-a4a7c4f69b47
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 95c9c1f7-671d-4d87-9155-53e01f037531
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 99b4727e-2a92-4d9f-bfe9-b0af7db321df
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 73257e51-0205-4462-b959-234c89eb43f0
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: e9afec5f-5585-401e-83f2-34f7f2a5c26e
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: b4c54a46-8eb3-4740-b2a3-bc4808570173
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: 171f9de4-f703-4ab4-b880-7aab174f0834
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: b4fe36ab-664c-49b7-86f1-8dc4c16365a2
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 29865d5a-e574-4623-ac08-8f183e2721fe
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 104245b2-d61d-4bb4-b51c-df541b570b69
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: 020095c0-e430-429c-8d66-d7e19efea94c
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 1444ee84-40f7-4f7a-91b6-badc2b5138b3
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 3fd59db6-cddc-4c20-9971-f2e83193331e
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 349d5ece-c754-4aa9-9f6c-b0a92af3a4b5
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: eac5d5b8-b409-46e2-a690-ea2a8f8d97a0
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 96690683-457f-4c64-8401-0ba87ddd359d
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 18eafd62-f6a4-4de6-9b72-5ee1570e391c
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: a305e07e-06a5-4b08-9de4-251fbd184612
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: b90b969c-f6f7-43c5-84ef-e8babe1f6d7e
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 3bc34ae9-6ddc-4f90-8137-6b6d5abca842
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 452acb63-8131-42aa-8594-4c81e9f5d33f
		summarizeBy: sum
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 34b4d7d0-77ff-40c8-af7c-b63e6e2f46bb
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: db1b035c-7b6e-4ed8-ac7e-441d01351918
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column 'mes.1'
		dataType: string
		lineageTag: 484f32a6-82f3-4715-aed1-452a8f76fdda
		summarizeBy: none
		sourceColumn: mes.1

		annotation SummarizationSetBy = Automatic

	column id_sede_1
		dataType: int64
		formatString: 0
		lineageTag: 65daff14-fb46-4169-b962-3f5b63a065ed
		summarizeBy: sum
		sourceColumn: id_sede_1

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: bac41c1d-715e-4802-bdc2-f448e8e05521
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	column Column29
		dataType: string
		lineageTag: f45aa733-e0c3-4e79-a065-540584166d64
		summarizeBy: none
		sourceColumn: Column29

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: f18a4dad-deff-496d-9e3a-cbf33358a329
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column datekey_2
		dataType: int64
		formatString: 0
		lineageTag: fce82e48-ab56-436b-a1a2-08070687daf7
		summarizeBy: sum
		sourceColumn: datekey_2

		annotation SummarizationSetBy = Automatic

	column 'Canal.1'
		dataType: int64
		formatString: 0
		lineageTag: 02d4b5aa-c779-4b7e-967e-7be58387755c
		summarizeBy: sum
		sourceColumn: Canal.1

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: a9addad3-5e04-436c-ac7c-6b91a617e864
		summarizeBy: sum
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: aa35d323-3681-460e-9d63-56216dde2daf
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Vehiculo
		dataType: int64
		formatString: 0
		lineageTag: c6d921ab-e210-4ac4-9c0c-64b963e31f4b
		summarizeBy: sum
		sourceColumn: Vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo Vehículo'
		dataType: double
		lineageTag: 5163cc6f-f86c-49f0-baec-9c45625ddde2
		summarizeBy: sum
		sourceColumn: Costo Vehículo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Venta sin IGV'
		dataType: double
		lineageTag: 420ec50a-a84c-490e-a93c-6632f202e48e
		summarizeBy: sum
		sourceColumn: Precio Venta sin IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IGV
		dataType: double
		lineageTag: 0d6f33b4-ee61-4f51-b79e-ca196ab999cc
		summarizeBy: sum
		sourceColumn: IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: int64
		formatString: 0
		lineageTag: eeaf82a6-2057-45e6-b04f-eb715f1ec31a
		summarizeBy: sum
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 7bd8443c-b45b-496b-8392-94954316c1e9
		summarizeBy: sum
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Column41
		dataType: string
		lineageTag: e952bf36-2c30-4c56-b55d-5b171812b42b
		summarizeBy: none
		sourceColumn: Column41

		annotation SummarizationSetBy = Automatic

	column 'Id.1'
		dataType: int64
		formatString: 0
		lineageTag: 71aa90e5-0c5b-45bc-bdec-36dc220b9961
		summarizeBy: sum
		sourceColumn: Id.1

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: a6b935a9-f421-4e04-8402-1b9ef6259c17
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 54cb094b-ac1a-4743-a2f5-06c987c79735
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: d847742b-0d4f-4322-8468-26bb05185056
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: d835c5ad-71d6-48f8-a334-40a4cb0648ac
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	column Column47
		dataType: string
		lineageTag: ba2a19db-ab14-444a-8780-1a16c0ffe805
		summarizeBy: none
		sourceColumn: Column47

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: ae2c7664-058d-4db9-93db-ca488b4b765c
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor_3
		dataType: string
		lineageTag: bbc2a3f1-b2c1-43c3-a6be-df0c6f468428
		summarizeBy: none
		sourceColumn: Vendedor_3

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 3f209e59-6f41-48dc-a14d-fffec669f816
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: f569d43b-071b-44eb-8b23-4faeb4dc9528
			defaultHierarchy: LocalDateTable_f69f899d-8cac-4c97-81fe-dd3467599618.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 3fa7d7b5-e9ab-4ed1-8967-333201b5ed11
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Hoja1 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Andreé Torres\Downloads\VentasVehiculos.xlsx"), null, true),
				    Hoja1_Sheet = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}, {"Column7", type any}, {"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}, {"Column11", type any}, {"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}, {"Column15", type any}, {"id_Cliente", Int64.Type}, {"Nombre", type text}, {"Column18", type any}, {"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}, {"Column24", type any}, {"periodo", Int64.Type}, {"mes", type text}, {"id_sede_1", Int64.Type}, {"ppto", Int64.Type}, {"Column29", type any}, {"ID", Int64.Type}, {"datekey_2", Int64.Type}, {"Canal", Int64.Type}, {"Cliente", Int64.Type}, {"Segmento", type text}, {"Vehiculo", Int64.Type}, {"Costo Vehículo", type number}, {"Precio Venta sin IGV", type number}, {"IGV", type number}, {"Sede", Int64.Type}, {"Vendedor", Int64.Type}, {"Column41", type any}, {"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}, {"Column47", type any}, {"ID_Vendedor", Int64.Type}, {"Vendedor_3", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"mes", "mes.1"}, {"Canal", "Canal.1"}, {"Id", "Id.1"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

